from .criar_cliente_service import criar_cliente_service
from .criar_produto_service import criar_produto_service
from .criar_plano_service import criar_plano_service
from .consultar_cliente_service import consultar_cliente_service
from .excluir_cliente_service import excluir_cliente_service
from .atualizar_cliente_service import atualizar_cliente_service
from .consultar_plano_service import consultar_plano_service