apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  labels:
    app: fastapi
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: meu-usuario/minha-api:latest # exemplo para uso
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: fastapi-config
